#-------------------------------
# Site Settings
title: Studio Loft Media
description: Elevate your craft. Master your media.
logo: '/images/brand/sl-logo-black-474x100.png'
logo_dark: '/images/brand/sl-logo-white-474x100.png'


#-------------------------------
# Color Scheme Settings
color_scheme:
  default: dark
  toggle: true


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Glossary'
      url: '/glossary/'
    - title: 'Videos'
      url: '/videos/'
    - title: 'Pages'
      submenu:
      - url: '/archive/'
        title: 'Archive'
      - url: '/contact'
        title: 'Contact'


#-------------------------------
# Author Settings
author:
  author_name: Gavin Hornak
  author_avatar: /images/profile/profile-256x256.jpg


#-------------------------------
# Hero Settings
hero:
  enable: false
  hero_avatar: /images/profile/profile-256x256.jpg
  hero_title: Hi! Iâ€™m Gavin ðŸ‘‹
  hero_subtitle: Engineering the future of media and technology
  hero_description: |
    I'm a broadcast technology leader and technologist with >15 years of experience in media production, digital content creation, and IT systems management.

    At Studio Loft Media, I highlight ideas, tools, and approaches that help streamline creative workflows. My mission is to empower creators and professionals to elevate their craft and master their media with confidence and expertise.
  hero_image: /images/01.jpg
  hero_image_caption: Elevate Your Craft. Master Your Media.
  hero_button_text: Explore Studio Loft
  hero_button_link: '/'


# Logos
logos:
  enable: false
  logos_title: Hero Bar
  logo_image:
    - alt: "Game Boy"
      image: "/images/1000.jpg"
    - alt: "Super Nintendo"
      image: "/images/1001.jpg"
    - alt: "Keyboard"
      image: "/images/1002.jpg"
    - alt: "Headphones"
      image: "/images/1003.jpg"
    - alt: "Mouse"
      image: "/images/1004.jpg"


#-------------------------------
# Section Blog Settings
blog:
  enable: true
  blog_title: Recent Articles


#-------------------------------
# Tags Section Settings
tags_section:
  enable: true
  tags_section_title: Topics
  tags:
    - tag: "Video"
      image: "/images/stock/crt-wall.webp"
    - tag: "Computing"
      image: "/images/stock/data-display.webp"
    - tag: "Technology"
      image: "/images/stock/processor.webp"
    - tag: "Security"
      image: "/images/stock/cybersecurity.webp"


#-------------------------------
# Videos Section Settings
videos_section:
  enable: true
  videos_section_title: Latest Videos


#-------------------------------
# Gallery Section Settings
gallery_section:
  enable: false
  gallery_section_title: Recent Infographics
  gallery:
    gallery_images:
      - alt: 'Rest'
        url: '/images/content/panels-v25-11.png'
        caption: 'The Ultimate Display Technology Comparison (2025)'
      - alt: 'Lifestyle'
        url: '/images/content/fiberopticcable.png'
        caption: 'The Ultimate Guide to Fiber Optic Cable Types'
      - alt: 'Hobby'
        url: '/images/102.jpg'
        caption: 'True friends are like stars â€” they shine brightest when the world feels dark.'
      - alt: 'Computers'
        url: '/images/103.jpg'
        caption: 'Every click opens a new chapter in an endless story.'
      - alt: 'Games'
        url: '/images/104.jpg'
        caption: 'Every level is a new opportunity to test your limits.'


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp_title: Insights Delivered
  mailchimp_description: Receive curated knowledge, productivity hacks, and tech tips across media and technology straight to your inbox. Elevate the way you learn, work, and create with confidence and expertise.
  mailchimp_identifier: media.us14.list-manage.com/subscribe/post?u=1b35216b36115ee8eec4a8be8&id=1e0f3f04aa # MailChimp form identifier.
  mailchimp_input_text: Your email address...
  mailchimp_button_text: Join Now


#-------------------------------
# Footer Settings
footer_description: Empowering the next generation of education in media, technology, and digital productivity.<br><br>est.2008


#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://youtube.com/@Studioloftmedia"}
- {icon: "fa-brands fa-tiktok", name: "TikTok", link: "https://tiktok.com/@studioloftmedia"}
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com/studioloft"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com/studioloft"}
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/company/studioloftmedia"}
- {icon: "fa-solid fa-rss", name: "Rss", link: "/feed.xml"}

# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: mdkprwaa # Add your form_id, Formspree (https://formspree.io/)
  button_text: Send Now


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test
  disqus_title: Start the conversation
  disqus_button_text: Show Comments


#-------------------------------
# Google Analytics
google_analytics: G-MX1J188CT9 # GA Tracking Id
